# Generated by Django 5.2.4 on 2025-07-26 16:52

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_head', models.ImageField(blank=True, null=True, upload_to='postings/')),
                ('slug', models.SlugField(default='default-slug', max_length=250, unique_for_date='post_date')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', django_ckeditor_5.fields.CKEditor5Field(default='Default body')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('liked_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
