# Generated by Django 5.0.6 on 2025-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='blog_tag',
            field=models.CharField(default='default-tag', max_length=225),
        ),
        migrations.AddField(
            model_name='posts',
            name='main_date',
            field=models.CharField(default='main-date', max_length=225),
        ),
    ]
